steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT} || exit 0']

  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
    
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT}',
        '--cache-from',
        'gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT}',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        '${_APP_NAME}-${_ENVIRONMENT}',
        '--image',
        'gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT}',
        '--platform',
        'managed',
        '--region',
        '${_REGION}',
        '--allow-unauthenticated',
      ]

timeout: 1200s
options:
  machineType: 'E2_HIGHCPU_8'